create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.items (
  id text primary key,
  label text not null check (char_length(label) between 3 and 80),
  description text not null check (char_length(description) between 8 and 240),
  category text not null check (char_length(category) between 2 and 40),
  image_url text not null,
  accent text not null default '#2f9c95',
  sort_order integer not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.votes (
  item_id text not null references public.items(id) on delete cascade,
  session_id text not null,
  user_id uuid references auth.users(id) on delete cascade,
  choice text not null check (choice in ('yes', 'no')),
  decision_ms integer check (decision_ms is null or decision_ms between 0 and 120000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (session_id, item_id)
);

create table if not exists public.vote_events (
  id bigint generated by default as identity primary key,
  item_id text not null references public.items(id) on delete cascade,
  session_id text not null,
  user_id uuid references auth.users(id) on delete set null,
  choice text not null check (choice in ('yes', 'no')),
  decision_ms integer check (decision_ms is null or decision_ms between 0 and 120000),
  created_at timestamptz not null default now()
);

create index if not exists votes_item_id_idx on public.votes(item_id);
create index if not exists votes_user_id_idx on public.votes(user_id);
create index if not exists vote_events_item_id_idx on public.vote_events(item_id);

revoke all on table public.profiles from anon, authenticated;
revoke all on table public.items from anon, authenticated;
revoke all on table public.votes from anon, authenticated;
revoke all on table public.vote_events from anon, authenticated;

grant usage on schema public to anon, authenticated, service_role;
grant select on table public.profiles to authenticated;
grant select, insert, update, delete on table public.profiles to service_role;
grant select on table public.items to anon, authenticated;
grant insert, update, delete on table public.items to authenticated;
grant select, insert, update, delete on table public.items to service_role;
grant select, insert, update, delete on table public.votes to anon, authenticated, service_role;
grant insert on table public.vote_events to anon, authenticated;
grant select, insert, update, delete on table public.vote_events to service_role;
grant usage, select on sequence public.vote_events_id_seq to anon, authenticated, service_role;

alter table public.profiles enable row level security;
alter table public.items enable row level security;
alter table public.votes enable row level security;
alter table public.vote_events enable row level security;

drop policy if exists "profiles can read own row" on public.profiles;
create policy "profiles can read own row"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

drop policy if exists "items are readable" on public.items;
create policy "items are readable"
on public.items
for select
to anon, authenticated
using (true);

drop policy if exists "admins can insert items" on public.items;
create policy "admins can insert items"
on public.items
for insert
to authenticated
with check (exists (
  select 1 from public.profiles
  where profiles.id = auth.uid()
  and profiles.role = 'admin'
));

drop policy if exists "admins can update items" on public.items;
create policy "admins can update items"
on public.items
for update
to authenticated
using (exists (
  select 1 from public.profiles
  where profiles.id = auth.uid()
  and profiles.role = 'admin'
))
with check (exists (
  select 1 from public.profiles
  where profiles.id = auth.uid()
  and profiles.role = 'admin'
));

drop policy if exists "votes are readable for realtime" on public.votes;
create policy "votes are readable for realtime"
on public.votes
for select
to anon, authenticated
using (true);

drop policy if exists "clients can insert votes" on public.votes;
create policy "clients can insert votes"
on public.votes
for insert
to anon, authenticated
with check (
  (auth.uid() is null and user_id is null and session_id like 'sv_%')
  or
  (auth.uid() = user_id and session_id = 'user_' || auth.uid()::text)
);

drop policy if exists "clients can update own votes" on public.votes;
create policy "clients can update own votes"
on public.votes
for update
to anon, authenticated
using (
  (auth.uid() is null and user_id is null and session_id like 'sv_%')
  or
  (auth.uid() = user_id and session_id = 'user_' || auth.uid()::text)
)
with check (
  (auth.uid() is null and user_id is null and session_id like 'sv_%')
  or
  (auth.uid() = user_id and session_id = 'user_' || auth.uid()::text)
);

drop policy if exists "clients can delete own votes" on public.votes;
create policy "clients can delete own votes"
on public.votes
for delete
to anon, authenticated
using (
  (auth.uid() is null and user_id is null and session_id like 'sv_%')
  or
  (auth.uid() = user_id and session_id = 'user_' || auth.uid()::text)
);

drop policy if exists "vote events can be inserted" on public.vote_events;
create policy "vote events can be inserted"
on public.vote_events
for insert
to anon, authenticated
with check (true);

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'items'
    ) then
      alter publication supabase_realtime add table public.items;
    end if;

    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'votes'
    ) then
      alter publication supabase_realtime add table public.votes;
    end if;
  end if;
end $$;
